# Generated by Django 3.2 on 2022-08-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='logo',
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(choices=[('fendi', 'fendi'), ('balenciaga', 'balenciaga')], max_length=40),
        ),
    ]
